"""001 Initial app models

Revision ID: 5314b919ed5e
Revises:
Create Date: 2025-11-26 13:05:49.170523

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5314b919ed5e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "levels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_levels")),
        sa.UniqueConstraint("name", name=op.f("uq_levels_name")),
    )
    # Pre-populate levels with standard belt names and ranks
    op.execute("""
    INSERT INTO levels (id, name, rank) VALUES (1, 'white', 1);
    INSERT INTO levels (id, name, rank) VALUES (2, 'yellow', 2);
    INSERT INTO levels (id, name, rank) VALUES (3, 'orange', 3);
    INSERT INTO levels (id, name, rank) VALUES (4, 'green', 4);
    INSERT INTO levels (id, name, rank) VALUES (5, 'blue', 5);
    INSERT INTO levels (id, name, rank) VALUES (6, 'brown', 6);
    INSERT INTO levels (id, name, rank) VALUES (7, 'black', 7);
    INSERT INTO levels (id, name, rank) VALUES (8, 'red-white', 8);
    INSERT INTO levels (id, name, rank) VALUES (9, 'red', 9);
    """)
    op.create_table(
        "locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_locations")),
        sa.UniqueConstraint("name", name=op.f("uq_locations_name")),
    )
    op.create_table(
        "payment_prices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("description", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_prices")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("tenant_schema", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint(
            "tenant_schema", "email", name="uq_shared_users_tenant_email"
        ),
        sa.UniqueConstraint(
            "tenant_schema", "username", name="uq_shared_users_tenant_username"
        ),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(
        op.f("ix_users_tenant_schema"), "users", ["tenant_schema"], unique=False
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=False)
    op.create_table(
        "members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("surname", sa.String(length=100), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column(
            "sex", sa.Enum("MALE", "FEMALE", "OTHER", name="sex"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "BANNED", "SUSPENDED", name="memberstatus"),
            nullable=False,
        ),
        sa.Column("date_of_enrolment", sa.Date(), nullable=False),
        sa.Column("level_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["level_id"], ["levels.id"], name=op.f("fk_members_level_id_levels")
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_members_location_id_locations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_members")),
    )
    op.create_index("idx_member_location", "members", ["location_id"], unique=False)
    op.create_index(
        "idx_member_name_surname", "members", ["name", "surname"], unique=False
    )
    op.create_index("idx_member_status", "members", ["status"], unique=False)
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("price_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("payment_date", sa.DateTime(), nullable=False),
        sa.Column("period_month", sa.Integer(), nullable=False),
        sa.Column("period_year", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["member_id"], ["members.id"], name=op.f("fk_payments_member_id_members")
        ),
        sa.ForeignKeyConstraint(
            ["price_id"],
            ["payment_prices.id"],
            name=op.f("fk_payments_price_id_payment_prices"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
    )
    op.create_index("idx_payment_member", "payments", ["member_id"], unique=False)
    op.create_index(
        "idx_payment_member_period",
        "payments",
        ["member_id", "period_year", "period_month"],
        unique=False,
    )
    op.create_index(
        "idx_payment_period", "payments", ["period_year", "period_month"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_payment_period", table_name="payments")
    op.drop_index("idx_payment_member_period", table_name="payments")
    op.drop_index("idx_payment_member", table_name="payments")
    op.drop_table("payments")
    op.drop_index("idx_member_status", table_name="members")
    op.drop_index("idx_member_name_surname", table_name="members")
    op.drop_index("idx_member_location", table_name="members")
    op.drop_table("members")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_tenant_schema"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("payment_prices")
    op.drop_table("locations")
    op.drop_table("levels")
    # ### end Alembic commands ###
